### ISSUE TITLE
EOF()

### ISSUE THREAD

**Issue by Zaineb-Hammouda** [DuncanMoyo/AirBnB_clone#28]
in our EOF method, i added a "print()" statement to print a newline before exiting cause the code snippet they gave us at the beginning of the project shows a new line after the user uses ctrl+D, as well as after doing this : 
**cat test_help | ./console.py
(hbnb)

Documented commands (type help <topic>):

EOF  help  quit
(hbnb)
$**

as u can see, in non_interactive mode, the console quits after executing the command and prints a newline at the end for the shell prompt so if i remove the "print()" statement from the EOF method we get this instead:

**zaineb@DESKTOP:~/alx/AirBnB_clone$ echo "help" | ./console.py
(hbnb)
Documented commands (type help <topic>):

EOF  all  create  destroy  help  quit  show  update

(hbnb) zaineb@DESKTOP:~/alx/AirBnB_clone$**

the newline gets removed.
the problem is, after some research i saw that u shoudn't add the print statement so idk if i should remove it and risk the checker saying it's wrong or leave it :p 
guess we'll have to wait for the checker and if it says stuff is wrong we can test that first to see if it gets corrected

**Comment by DuncanMoyo** [comment]
Yeah, technically you shouldn't need the `print()` since `cmd.Cmd` already handles that. I guess let us keep an eye on this one and we will see after the checker gets released
