### ISSUE TITLE
More unittests for the console

### ISSUE THREAD

**Issue by DuncanMoyo** [DuncanMoyo/AirBnB_clone#35]

**Comment by DuncanMoyo** [comment]
In the default function,  i added an if statement since we were getting an IndexError. This if statement checks to make sure that `i + 1` is within the range of valid indices for the args list before trying to access it.
Like so: ```
for i in range(1, len(args), 2):
                        if i + 1 < len(args):
                            x = cls + ' ' + args[0] + ' ' +\
                                args[i] + ' ' + args[i + 1]
                            v(x)
```

**Comment by Zaineb-Hammouda** [comment]
Why would it give an index out of range error? I think i already managed that no? With the else statement
